### PR TITLE
Custom contrast coding feature added along with various improvements

### PR DESCRIPTION
**Pull request by acp29**
- Factor levels and their coefficients now appear in order in which they first appear in GROUP (consistent with MATLAB)

- Added feature enabling users to code their own contrasts. The contrast coding scheme implemented is reported for each factor level in a cell array in the STATS output structure. STATS.coeff is now a matrix with columns 1-4 corresponding to the model coefficients, their standard errors, t-statistics and p-values.

- `coeffnames` field in STATS output structure now used. 

- Minor changes to format of grpnames to improve consistency with Matlab. Specifically, factors with numeric identifies in GROUP are returned as a cell array

- Minor bug fixes relating to evaluating input

### CODE REVIEW

**Review by pr0m1th3as — APPROVED** [review]
Great work Andy :+1:. I will try to have the multcompare function implemented by the end of the month so you can test it and perhaps make the necessary changes so that it can handle the stats structure output from anovan as well. Btw, thanks for paying attention to the coding style, I am currently trying to fix this in a number of old functions that are not well formatted and it's a tedious task. If you would like to keep error strings below 80 chars long you can always do:
```
error (strcat (["some long comment for error goes here "] ...
          [" and it continuous further down here."]));
```
and use `##` istead of `#` for full line comments

**Comment by acp29** [comment]
cool thanks for the tips Andreas 😊

——

Dr Andrew Penn (he/his)
Sussex Neuroscience
School of Life Sciences
University of Sussex
Brighton BN1 9QG
United Kingdom

Tel: +44 (0)1273 877049
E-mail: ***@***.******@***.***>

http://www.sussex.ac.uk/lifesci/pennlab/
http://www.researchgate.net/profile/Andrew_Penn
https://scholar.google.com/citations?user=pDxdZaoAAAAJ&hl=en
http://sussex.academia.edu/AndrewPenn




On 17 Aug 2022, at 00:27, Andreas Bertsatos ***@***.******@***.***>> wrote:



@pr0m1th3as approved this pull request.

Great work Andy 👍. I will try to have the multcompare function implemented by the end of the month so you can test it and perhaps make the necessary changes so that it can handle the stats structure output from anovan as well. Btw, thanks for paying attention to the coding style, I am currently trying to fix this in a number of old functions that are not well formatted and it's a tedious task. If you would like to keep error strings below 80 chars long you can always do:

error (strcat (["some long comment for error goes here "] ...
          [" and it continuous further down here."]));


and use ## istead of # for full line comments

**Comment by acp29** [comment]
BTW I 'think' I will be able to add 'nested' and 'random' options to anovan with relatively little extra code, although the implementation will be restricted to sstype 1

**Comment by acp29** [comment]
By the way heroic work you are doing with this package, keep it up!

——

Dr Andrew Penn (he/his)
Sussex Neuroscience
School of Life Sciences
University of Sussex
Brighton BN1 9QG
United Kingdom

Tel: +44 (0)1273 877049
E-mail: ***@***.******@***.***>

http://www.sussex.ac.uk/lifesci/pennlab/
http://www.researchgate.net/profile/Andrew_Penn
https://scholar.google.com/citations?user=pDxdZaoAAAAJ&hl=en
http://sussex.academia.edu/AndrewPenn




On 17 Aug 2022, at 00:32, Andrew Penn ***@***.******@***.***>> wrote:

cool thanks for the tips Andreas 😊

——

Dr Andrew Penn (he/his)
Sussex Neuroscience
School of Life Sciences
University of Sussex
Brighton BN1 9QG
United Kingdom

Tel: +44 (0)1273 877049
E-mail: ***@***.******@***.***>

http://www.sussex.ac.uk/lifesci/pennlab/
http://www.researchgate.net/profile/Andrew_Penn
https://scholar.google.com/citations?user=pDxdZaoAAAAJ&hl=en
http://sussex.academia.edu/AndrewPenn




On 17 Aug 2022, at 00:27, Andreas Bertsatos ***@***.******@***.***>> wrote:



@pr0m1th3as approved this pull request.

Great work Andy 👍. I will try to have the multcompare function implemented by the end of the month so you can test it and perhaps make the necessary changes so that it can handle the stats structure output from anovan as well. Btw, thanks for paying attention to the coding style, I am currently trying to fix this in a number of old functions that are not well formatted and it's a tedious task. If you would like to keep error strings below 80 chars long you can always do:

error (strcat (["some long comment for error goes here "] ...
          [" and it continuous further down here."]));


and use ## istead of # for full line comments

**Pull request merged**
