### PR TITLE
mean/median/str/var - update author name/email

### PR DESCRIPTION
**Pull request by NRJank**

### CODE REVIEW

**Comment by pr0m1th3as** [comment]
Is there something wrong with this PR? Can I merge it to main so your name and email are displayed properly?

**Comment by NRJank** [comment]
there's another following that included BIST corrections and should be the 'last' one. it'll be arriving in a moment.

**Comment by pr0m1th3as** [comment]
ok

**Comment by NRJank** [comment]
thanks. thought the re-submit would be faster and then I got sidetracked :)

**Pull request closed without merging**
